version: "3.5"

services:
  php-apache:
    build:
      context: .
      dockerfile: .docker/php-apache/Dockerfile
    container_name: ${CONTAINER_NAME_APACHE}
    environment:
      - "APACHE_LOG_DIR:/logs"
    ports:
      - ${PORT}:80
      - ${PORT_SSL}:443
    volumes:
      - ./.docker/php-apache/sites-available:/etc/apache2/sites-available
      - ./.docker/php-apache/apache-ssl:/etc/apache2/sites-available/ssl
      - ./webapp:/var/www/html

  composer:
        image: "composer"
        container_name: ${CONTAINER_NAME_COMPOSER}
        volumes:
            - "./webapp:/app"
        command: install